**Difference between PCA and LDA**


LDA is supervised and PCA is unsupervised


LDA is used for maximizing the separation between two or more classes, whereas the PCA is used for maximizing the variation

In [1]:
#Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_digits

Load Digits

In [3]:
dataset=load_digits()

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [5]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [6]:
df.isnull().sum()

pixel_0_0    0
pixel_0_1    0
pixel_0_2    0
pixel_0_3    0
pixel_0_4    0
            ..
pixel_7_3    0
pixel_7_4    0
pixel_7_5    0
pixel_7_6    0
pixel_7_7    0
Length: 64, dtype: int64

In [7]:
#Adding target to Dataset
df["target"]=dataset.target

In [8]:
# Feature of the images
x_df=df.drop("target",axis=1)

#dependent feature
y_df=df["target"]

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.20, random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [12]:
#Discriminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [13]:
df["target"].nunique()

10

In [14]:
lda=LinearDiscriminantAnalysis(n_components=min(10-1,64))
lda

LinearDiscriminantAnalysis(n_components=9)

In [15]:
x_train=lda.fit_transform(x_train,y_train)
x_test=lda.transform(x_test)

In [16]:
x_train.shape

(1437, 9)

In [17]:
x_test.shape

(360, 9)

In [18]:
lda.coef_

array([[-2.17191310e-17,  6.40269680e-02, -6.90688884e-02,
         7.94874045e-01, -3.44326814e-01, -2.59096099e+00,
         3.93735990e-01, -1.25179637e-01,  2.55392176e-01,
        -5.85977175e-01, -9.14104254e-02,  1.40731821e-02,
         1.45945710e+00,  4.99665732e-01, -7.68295397e-02,
        -4.29161629e-01, -6.78512748e-01,  5.99949935e-01,
         1.38072390e-01,  2.74695492e-01, -2.24635714e+00,
         3.73034571e+00, -2.16629991e-01,  1.21448598e-01,
         1.32603665e-01,  1.19466370e+00,  8.87006675e-01,
        -5.64283368e-01, -3.81730207e+00, -2.12649237e+00,
         1.76649102e+00,  2.44124002e-02,  1.41910066e-16,
         9.26315574e-01,  9.04079492e-01, -2.88810857e+00,
        -1.51320783e+00, -2.21578407e+00,  2.14501310e+00,
         1.63396483e-15,  1.61681037e-02, -4.64040126e-01,
         2.40758605e+00, -3.15165463e+00, -2.98952624e+00,
         8.25749833e-01,  7.80171145e-01,  2.73960055e-01,
        -3.78232998e-01, -1.02377418e+00,  7.54727951e-0

In [19]:
# The explained variance (how much variance is explained by each component)
explained_variance_ratio=lda.explained_variance_ratio_
explained_variance_ratio

array([0.27851663, 0.19023768, 0.17379022, 0.11077975, 0.08773235,
       0.0654018 , 0.04249174, 0.02968284, 0.02136698])

In [20]:
pd.DataFrame(explained_variance_ratio)

0
0  0.278517
1  0.190238
2  0.173790
3  0.110780
4  0.087732
5  0.065402
6  0.042492
7  0.029683
8  0.021367

In [21]:
pd.DataFrame(lda.coef_)

0         1         2         3         4         5         6   \
0 -2.171913e-17  0.064027 -0.069069  0.794874 -0.344327 -2.590961  0.393736   
1 -1.119324e-17 -0.085154  0.163168  0.222577 -1.503485  1.215410 -0.610883   
2 -9.174540e-18 -0.305547 -0.279365 -0.306241 -0.443283  0.664740  0.003898   
3 -3.701735e-17 -0.255179 -0.707246  1.458020  0.824520  0.991619  0.014636   
4  4.797148e-17  0.173973 -0.223263 -2.480686  0.153363 -3.047432 -1.175886   
5  8.486166e-17 -0.101196  2.452258  0.004712  0.950605  2.725921  2.019970   
6 -8.640054e-17  0.150523 -1.446359 -1.287643  0.300279 -0.850690 -0.594154   
7  2.874593e-17  0.406993 -0.275671  0.674008  0.349959  1.027856  1.197214   
8  6.836416e-18 -0.061331  0.494574 -0.637284  0.007930  0.214087 -1.238554   
9  8.851089e-18  0.027619  0.067878  1.382931 -0.159421 -0.480146  0.084235   

         7         8         9   ...        54        55        56        57  \
0 -0.125180  0.255392 -0.585977  ... -1.574156  0.011177  0.134645  0.127487   
1  0.059487 -0.309697 -0.210663  ... -0.338694  0.774458 -0.194918  0.028469   
2 -0.243514 -0.286908  1.122831  ...  1.802064 -0.774040  0.490996  0.253504   
3 -0.350981 -0.332749  0.829879  ...  0.533975 -0.020085  0.347890  0.568174   
4  0.879830  0.255840  0.702461  ... -0.917880  0.305623 -0.564291 -0.315679   
5 -0.723180  0.066529 -0.483732  ... -1.452409  0.118510  0.081802  0.251236   
6  0.048948  0.139691 -0.512399  ...  1.018744 -1.172957 -0.138199 -0.050293   
7  0.781560  0.173791 -0.493426  ...  0.005733  0.518384 -0.130773 -0.887491   
8  0.018046  0.064827 -0.174585  ...  0.500099 -0.059687 -0.126167  0.042478   
9 -0.341904  0.022188 -0.185442  ...  0.283993  0.292787  0.074272 -0.038718   

         58        59        60        61        62        63  
0 -0.220429  0.000094 -0.000358 -1.234979  0.582503 -0.791776  
1 -1.723047  0.208902  1.085769  1.520080 -0.667857  1.002990  
2  0.558696  0.570668  0.401107  2.389980  3.064687  0.276569  
3  1.105714 -0.147016  0.275667  0.676064 -0.218842 -0.598142  
4 -0.154567 -0.383699  1.170201 -2.284139 -0.792583  0.406673  
5  0.878116  0.945965 -1.382399 -0.250280 -0.147110 -0.956488  
6  0.679642  0.057648 -0.213798  0.752617 -0.394664  0.183167  
7  0.709178 -0.543240 -3.167748 -0.186730 -1.218680  0.534538  
8 -1.465869  0.133605  0.815247 -1.175266 -0.019505  0.518368  
9 -0.261032 -0.837479  0.969992 -0.509517 -0.188026 -0.678757  

[10 rows x 64 columns]

In [22]:
sum(explained_variance_ratio)

0.9999999999999999

In [23]:
x_train.shape,x_test.shape

((1437, 9), (360, 9))

In [24]:
# import Random Forest classifier
from sklearn.ensemble import RandomForestClassifier

# instantiate the classifier
clf = RandomForestClassifier(random_state=0,n_estimators= 100)

# fit the classifier with x and y data
clf.fit(x_train, y_train)

RandomForestClassifier(random_state=0)

In [25]:
y_pred=clf.predict(x_test)
y_pred

array([6, 9, 3, 7, 2, 1, 5, 2, 5, 3, 1, 9, 4, 0, 4, 2, 3, 7, 8, 8, 4, 3,
       9, 7, 5, 6, 3, 5, 6, 3, 4, 9, 2, 4, 4, 6, 9, 4, 7, 6, 6, 9, 1, 3,
       6, 1, 3, 0, 6, 5, 5, 1, 9, 5, 6, 0, 9, 0, 0, 1, 3, 4, 5, 2, 4, 5,
       7, 0, 7, 5, 9, 5, 5, 4, 7, 0, 7, 5, 5, 9, 9, 0, 2, 3, 8, 0, 6, 4,
       4, 9, 1, 2, 8, 3, 5, 2, 9, 4, 4, 4, 4, 3, 5, 3, 1, 3, 5, 9, 4, 2,
       7, 7, 4, 4, 1, 9, 2, 7, 8, 7, 2, 6, 9, 4, 0, 7, 2, 7, 5, 8, 7, 5,
       7, 9, 0, 6, 6, 4, 2, 8, 0, 9, 4, 6, 9, 9, 6, 9, 0, 5, 5, 6, 6, 0,
       6, 4, 3, 9, 3, 7, 7, 2, 9, 0, 4, 5, 3, 6, 5, 8, 9, 8, 4, 2, 1, 3,
       7, 7, 2, 2, 3, 9, 8, 0, 3, 2, 2, 5, 6, 9, 9, 4, 1, 5, 4, 2, 3, 6,
       4, 8, 5, 9, 5, 7, 8, 9, 4, 8, 1, 5, 4, 4, 9, 6, 1, 8, 6, 0, 4, 5,
       2, 7, 4, 6, 4, 5, 6, 0, 3, 2, 3, 6, 7, 1, 9, 1, 4, 7, 6, 9, 1, 5,
       5, 1, 4, 1, 8, 8, 9, 8, 7, 6, 2, 2, 2, 3, 4, 8, 8, 3, 6, 0, 3, 7,
       7, 0, 1, 0, 4, 5, 1, 5, 3, 6, 0, 4, 1, 0, 0, 3, 6, 5, 9, 7, 3, 5,
       5, 9, 9, 8, 5, 3, 3, 2, 0, 5, 8, 3, 4, 0, 2,

In [26]:
accuracy_score(y_test,y_pred)

0.9527777777777777

In [27]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

cm

array([[31,  0,  0,  1,  1,  0,  0,  0,  0,  0],
       [ 0, 27,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1, 31,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 33,  0,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 45,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 45,  0,  0,  1,  1],
       [ 0,  0,  0,  0,  1,  0, 34,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 33,  0,  1],
       [ 0,  1,  0,  0,  0,  0,  0,  0, 28,  1],
       [ 0,  0,  0,  1,  0,  0,  0,  1,  2, 36]])

In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.94      0.97        33
           1       0.93      0.96      0.95        28
           2       0.97      0.94      0.95        33
           3       0.92      0.97      0.94        34
           4       0.96      0.98      0.97        46
           5       0.98      0.96      0.97        47
           6       1.00      0.97      0.99        35
           7       0.94      0.97      0.96        34
           8       0.90      0.93      0.92        30
           9       0.92      0.90      0.91        40

    accuracy                           0.95       360
   macro avg       0.95      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360



In [29]:
import plotly.express as px
fig = px.scatter(df, x = x_train[:,8], y = y_train,
                 labels={
                     "x": "LD1",
                     "y": "LD2",
                 },
                 opacity=1, color = y_train)


fig.update_layout(dict(plot_bgcolor = 'white'))
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black')

fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='lightgrey',
                 zeroline=True, zerolinewidth=1, zerolinecolor='lightgrey',
                 showline=True, linewidth=1, linecolor='black')


fig.update_layout(title_text="LDA Scatter Plot")

fig.update_traces(marker=dict(size=3))

fig.show()

In [30]:
import plotly.express as px
fig = px.scatter_3d(df, x = x_train[:,0], y = y_train, z = x_train[:,1],
                    labels={
                        "x": "LD1",
                        "y": "LD2",
                        "z": "LD3"
                    },
                    opacity=1, color = y_train)

fig.update_layout(scene=dict(xaxis_backgroundcolor="white",
                             yaxis_backgroundcolor="white",
                             zaxis_backgroundcolor="white"))

fig.update_layout(scene=dict(xaxis_showgrid=True, xaxis_gridwidth=1, xaxis_gridcolor='lightgrey',
                             xaxis_zeroline=True, xaxis_zerolinewidth=1, xaxis_zerolinecolor='lightgrey',
                             xaxis_showline=True, xaxis_linewidth=1, xaxis_linecolor='black',
                             yaxis_showgrid=True, yaxis_gridwidth=1, yaxis_gridcolor='lightgrey',
                             yaxis_zeroline=True, yaxis_zerolinewidth=1, yaxis_zerolinecolor='lightgrey',
                             yaxis_showline=True, yaxis_linewidth=1, yaxis_linecolor='black',
                             zaxis_showgrid=True, zaxis_gridwidth=1, zaxis_gridcolor='lightgrey',
                             zaxis_zeroline=True, zaxis_zerolinewidth=1, zaxis_zerolinecolor='lightgrey',
                             zaxis_showline=True, zaxis_linewidth=1, zaxis_linecolor='black'))

fig.update_layout(title_text="3D LDA Scatter Plot")

fig.update_traces(marker=dict(size=3))
